<?php

namespace App\Http\Controllers;
use App\Models\Products;
use App\Models\Productscars;
use App\Models\Pedidos;
use App\Models\Category;
use App\Models\Address;
use Illuminate\Http\Request;

class ProductsController extends Controller
{
    public function NovosProdutoFicticios(){
        $Produtos = new Products();
        $Produtos->name_product  = 'Americano'; 
        $Produtos->category_product = 'Lanches';
        $Produtos->valor_product = '13'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img1.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'X EGG'; 
        $Produtos->category_product = 'Lanches';
        $Produtos->valor_product = '10'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img2.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'X-Calabresa'; 
        $Produtos->category_product = 'Lanches';
        $Produtos->valor_product = '15'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img3.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'X-Bacon'; 
        $Produtos->category_product = 'Lanches';
        $Produtos->valor_product = '22'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img4.png';
        $Produtos->save();
        $Produtos->name_product  = 'Quatro-Queijos'; 
        $Produtos->category_product = 'Lanches';
        $Produtos->valor_product = '13'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img5.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'X-Frango'; 
        $Produtos->category_product = 'Lanches';
        $Produtos->valor_product = '14'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img6.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'X-Salada'; 
        $Produtos->category_product = 'Lanches';
        $Produtos->valor_product = '7'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img7.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'Coca-Cola'; 
        $Produtos->category_product = 'Bebidas';
        $Produtos->valor_product = '5'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '250 ml';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img8.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'Fanta Laranja'; 
        $Produtos->category_product = 'Bebidas';
        $Produtos->valor_product = '5'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '250 ml';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img9.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'Guarana'; 
        $Produtos->category_product = 'Bebidas';
        $Produtos->valor_product = '5'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '250 ml';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img10.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'Fanta Uva'; 
        $Produtos->category_product = 'Bebidas';
        $Produtos->valor_product = '5'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '250 ml';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img11.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'Pepsi'; 
        $Produtos->category_product = 'Bebidas';
        $Produtos->valor_product = '5'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '250 ml';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img12.png';
        $Produtos->save();
        $Categorias = new Category();
        $Categorias->category = 'Lanches';
        $Categorias->time = date('H:i:s'); 
        $Categorias->date = date('d/m/Y');
        $Categorias->save();
        $Categorias = new Category();
        $Categorias->category = 'Bebidas';
        $Categorias->time = date('H:i:s'); 
        $Categorias->date = date('d/m/Y');
        $Categorias->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'Completão'; 
        $Produtos->category_product = 'Lanches';
        $Produtos->valor_product = '18'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img13.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'Lombinho'; 
        $Produtos->category_product = 'Lanches';
        $Produtos->valor_product = '20'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img14.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'X-Burguer'; 
        $Produtos->category_product = 'Lanches';
        $Produtos->valor_product = '11'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img15.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'Rucula'; 
        $Produtos->category_product = 'Lanches';
        $Produtos->valor_product = '19'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img16.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'Churrasco'; 
        $Produtos->category_product = 'Lanches';
        $Produtos->valor_product = '19'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img17.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'BacomCheddar'; 
        $Produtos->category_product = 'Lanches';
        $Produtos->valor_product = '20'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img18.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'Acebolado'; 
        $Produtos->category_product = 'Lanches';
        $Produtos->valor_product = '20'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img19.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'Coca-Cola'; 
        $Produtos->category_product = 'Bebidas';
        $Produtos->valor_product = '10'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '2 L';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img20.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'Fanta Laranja'; 
        $Produtos->category_product = 'Bebidas';
        $Produtos->valor_product = '10'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '2 L';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img21.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'Fanta Uva'; 
        $Produtos->category_product = 'Bebidas';
        $Produtos->valor_product = '10'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '2 L';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img22.png';
        $Produtos->save();
        $Produtos = new Products();
        $Produtos->name_product  = 'Guarana Kuat'; 
        $Produtos->category_product = 'Bebidas';
        $Produtos->valor_product = '10'; 
        $Produtos->descricao_product = '';
        $Produtos->metrica = '2 L';
        $Produtos->time = date('H:i:s'); 
        $Produtos->date = date('d/m/Y');
        $Produtos->qt = '1';
        $Produtos->img_product1 = 'img23.png';
        $Produtos->save();
        return redirect('/.');
    } 
    public function DeleteProdutoFicticios(){
        Pedidos::where('date','!=', 1)->delete();
        Products::where('date','!=', 1)->delete();
        Category::where('date','!=', 1)->delete();
        Productscars::where('date','!=', 1)->delete();
        Address::where('cep','!=', 1)->delete();
        return redirect('/');
    }
    public function CadastrarProduto(Request $request){
        $cadastro = new Products();
        $cadastro->name_product  = $request->name_product; 
        $cadastro->category_product = $request->category_product; 
        $cadastro->valor_product = $request->valor_product; 
        $cadastro->descricao_product = $request->descricao_product; 
        $cadastro->metrica = $request->metrica; 
        $cadastro->time = date('H:i:s'); 
        $cadastro->date = date('d/m/Y');
        $cadastro->qt = '1';
        //Upload da Imagem
        if($request->hasFile('img_product') && $request->file('img_product')->isValid()) {
            $requestImage = $request->img_product;
            $extension = $requestImage->extension();
            $imagemName = md5($requestImage->getClientOriginalName() . strtotime("now")) . "." . $extension;
            $requestImage->move(public_path('img/produto'), $imagemName);
            $cadastro->img_product1 = $imagemName;
        }   
        $cadastro->save();
        return redirect('/admin/produtos');
    } 
    public function DeleteProduto(Request $request){
        $cadastro = Products::find($request->id);
        $cadastro->delete();
        $Produtos = Products::All();
        return view('AdminProduto',['Produtos'=>$Produtos]);
    }
    public function CadastrarCategoria(Request $request){
        $cadastro = new Category();
        $cadastro->category = $request->category;
        $cadastro->time = date('H:i:s'); 
        $cadastro->date = date('d/m/Y');
        $cadastro->save();
        return redirect('admin/category');
    }         
    public function DeletarCategoria(Request $request){
        $cadastro = Category::find($request->id);
        $cadastro->delete();
        $Category = Category::All();
        return view('AdminCategory',['Produtos'=>$Category]);
    }  
}
